export const columns = [
  {
    id: 1,
    field: 'IngredientName',
    headerName: 'Ingredient Name',
    type: 'name',
    align: 'left',
    editable: false,
  },
  {
    id: 2,
    field: 'CategoryTitle',
    headerName: 'Category',
    type: 'name',
    align: 'left',
    editable: false,
  },
  {
    id: 3,
    field: 'RecipeSubCategoryTitle',
    headerName: 'Sub Category',
    type: 'name',
    align: 'left',
    editable: false,
  },
  {
    id: 4,
    field: 'BiologicalHazardTitle',
    headerName: 'Biological Hazard',
    type: 'name',
    align: 'left',
    editable: false,
  },
  {
    id: 5,
    field: 'Status',
    headerName: 'HAZARD ADDRESSED BY SUPPLIER',
    type: 'check',
    align: 'center',
    editable: false,
  },
  { id: 6, field: 'edit', headerName: '', type: 'action', align: 'center', editable: false },
  {
    id: 7,
    field: 'Process',
    headerName: 'Process',
    type: 'select',
    align: 'left',
    editable: false,
  },
  {
    id: 8,
    field: 'MinUnits',
    headerName: 'Min Units',
    type: 'input',
    align: 'left',
    editable: false,
  },
  {
    id: 9,
    field: 'MaxUnits',
    headerName: 'Max Units',
    type: 'input',
    align: 'left',
    editable: false,
  },
  {
    id: 10,
    field: 'Duration',
    headerName: 'Duration',
    type: 'input',
    align: 'left',
    editable: false,
  },
  {
    id: 11,
    field: 'Interval',
    headerName: 'Interval',
    type: 'select',
    align: 'left',
    editable: false,
  },
]
